### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by fde-fde** [barryZZJ/ucas_course_to_calendar#2]
![image](https://user-images.githubusercontent.com/62043427/190859278-6ad871d4-b7aa-49a5-a1f4-e7a984166b5e.png)
大佬，这是什么问题啊

**Comment by barryZZJ** [comment]
首先，这学期第一天是8.22，是第二周开始上的课。
其次，你能不能把报错信息完整复制过来，截图看着不全我看不出来具体哪报错了。
可以先检查一下jsessionid有没有错，或者重新登录换一个新的值试试。

**Comment by barryZZJ** [comment]
#3
