### ISSUE TITLE
大佬，怎么回事啊

### ISSUE THREAD

**Issue by fde-fde** [barryZZJ/ucas_course_to_calendar#3]
![34{%OPM1TUSEB2L9 _ L@59](https://user-images.githubusercontent.com/62043427/190903119-3382b35e-2ece-4770-9ae4-a355affba7e8.png)
![~ER~S~PHW71`3YOI$6GDK C](https://user-images.githubusercontent.com/62043427/190903123-91d3c66f-e41a-4560-bfb6-4c4376340c35.png)
![8JNW9 T9SHU8S$TW_JQK1P4](https://user-images.githubusercontent.com/62043427/190903131-90cdeb71-9ea4-4191-b713-2f781a355785.png)

**Comment by barryZZJ** [comment]
检查一下你的浏览器能正常访问 https://jwxk.ucas.ac.cn/courseManage/main 吗，报的是代理服务器错误，检查一下你代码或者pycharm是不是走代理了

**Comment by fde-fde** [comment]
网页打开是这的，请问没个学校的选课系统都可以导入下来吗？



---原始邮件---
发件人: "Zejun ***@***.***&gt;
发送时间: 2022年9月18日(周日) 晚上10:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [barryZZJ/ucas_course_to_calendar] 大佬，怎么回事啊 (Issue #3)




 
检查一下你的浏览器能正常访问https://jwxk.ucas.ac.cn/courseManage/main吗

**Comment by barryZZJ** [comment]
你重新打一遍，错字太多了😂这个脚本是只适配国科大的

**Comment by fde-fde** [comment]
栓q&nbsp; 我就说么，进去教务系统都需要密码的。能开发一个每个学校都可以的代码吗😂



---原始邮件---
发件人: "Zejun ***@***.***&gt;
发送时间: 2022年9月18日(周日) 晚上10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [barryZZJ/ucas_course_to_calendar] 大佬，怎么回事啊 (Issue #3)




 
你重新打一遍，错字太多了😂这个脚本是只适配国科大的

**Comment by barryZZJ** [comment]
很明显不行，可以参考我的代码适配你自己的学校。

**Comment by fde-fde** [comment]
好的好的



---原始邮件---
发件人: "Zejun ***@***.***&gt;
发送时间: 2022年9月18日(周日) 晚上10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [barryZZJ/ucas_course_to_calendar] 大佬，怎么回事啊 (Issue #3)




 
很明显不行，可以参考我的代码适配你自己的学校。
