### ISSUE TITLE
想问一下怎么导出csv文件呢

### ISSUE THREAD

**Issue by cxlcjs1** [barryZZJ/ucas_course_to_calendar#4]
双击.exe文件，输入日期和序号之后，会默认生成.ics文件，然后在黑框里没有1和2的选项，想问一下作者大大怎么生成.csv文件呀？

**Comment by barryZZJ** [comment]
1. 我没有实现生成csv文件，为什么需要csv呢？你想要生成的csv文件内容是怎样的？
2. “黑框里没有1和2的选项”是什么意思

**Comment by barryZZJ** [comment]
你要找的是这个吧：https://github.com/Windy810/ucas_course_to_wakeup
不过一开始我的代码有个bug（#1），他fork的时候我还没有修改，你可以提醒他merge一下我的代码

**Comment by cxlcjs1** [comment]
好滴好滴，太谢谢了，是的，我要找的是这个网址，谢谢作者大大

陈享利
***@***.***

签名由 网易灵犀办公 定制


Original:
From:Zejun Zhou< ***@***.***>Date:2022-09-21 09:51:02To:barryZZJ/ucas_course_to_calendar< ***@***.***>Cc:cxlcjs1< ***@***.***>、Author< ***@***.***>Subject:Re: [barryZZJ/ucas_course_to_calendar] 想问一下怎么导出csv文件呢 (Issue #4)
你要找的是这个吧：https://github.com/Windy810/ucas_course_to_wakeup
 不过一开始我的代码有个bug（#1），他fork的时候我还没有修改，你可以提醒他merge一下我的代码

**Comment by cxlcjs1** [comment]
哈哈哈哈哈哈哈哈哈找错网址了

陈享利
***@***.***

签名由 网易灵犀办公 定制


Original:
From:Zejun Zhou< ***@***.***>Date:2022-09-21 09:46:25To:barryZZJ/ucas_course_to_calendar< ***@***.***>Cc:cxlcjs1< ***@***.***>、Author< ***@***.***>Subject:Re: [barryZZJ/ucas_course_to_calendar] 想问一下怎么导出csv文件呢 (Issue #4)
我没有实现生成csv文件，为什么需要csv呢？你想要生成的csv文件内容是怎样的？ “黑框里没有1和2的选项”是什么意思—
